version: '3.7'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: p2p
      POSTGRES_DB: p2p
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
