name: Daily Backup of Operational Data

on:
  schedule:
  - cron: "0 0 * 1 1"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: git pull, build and deploy
      run: |
        echo geil,
        sshpass -p ${{ secrets.pw }} ssh root@95.216.150.10 -o StrictHostKeyChecking=no < ./trigger-operational-data-backup.sh
